baseURL = "/"
languageCode = "en-us"
title = "Shankar Kumar"
publishdir = "expectopatronm.github.io"

MetaDataFormat = "toml"


['params']
description = "Applied Machine Learning Enthusiast. Interested in Data Science, Autonomous Systems, Computer Vision and Embedded Intelligence"  
  
github = "https://github.com/expectopatronm"
linkedin = "https://www.linkedin.com/in/shankar-kumar-40503477/"  